[package]
name = "MangaReader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.6", features = ["image"]}
iced_native = "0.7.0"
zip = "0.6"
xdg = "2.4.*"
